services:
  mysql:
    image: mysql:8.0
    container_name: posty-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posty
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --performance-schema=ON
